export default {
  products: [

    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },
    {
      _id: '1',
      name: "Nike air zoom pegasis 37",
      category: "Men's running shoes",
      image: "/images/grey.png",
      color: "3 colors",
      brand: "Nike",
      price: "10000",
      rating: 4.5,
      numRating: 10,
    },

    {
      _id: '2',
      name: "nike running",
      category: "Men",
      image: "/images/grey.png",
      brand: "Nike",
      price: "20000",
      rating: 4,
      numRating: 100,
    },
    {
      _id: '3',
      name: "reebok running",
      category: "Men",
      image: "/images/grey.png",
      brand: "Reebok",
      price: "50000",
      rating: 3.5,
      numRating: 150,
    },
    {
      _id: '4',
      name: "women running",
      category: "Women",
      image: "/images/grey.png",
      brand: "Reebok",
      price: "40000",
      rating: 3.5,
      numRating: 150,
    },
    {
      _id: '5',
      name: "women Casual",
      category: "Women",
      image: "./images/grey.png",
      brand: "Nike",
      price: "4500",
      rating: 3.5,
      numRating: 150,
    },
    {
      _id: '6',
      name: "women casual",
      category: "Women",
      image: "./images/grey.png",
      brand: "bahamas",
      price: "4000",
      rating: 3.5,
      numRating: 150,
    },
    {
      _id: '7',
      name: "Men casual",
      category: "Men",
      image: "./images/grey.png",
      brand: "Redtape",
      price: "2500",
      rating: 4.5,
      numRating: 1050,
    },

  ]

}